image:
  file: ./.docker/gitpod/.gitpod.dockerfile

ports:
  - port: 8080
    visibility: public

tasks:
    - init: |
        echo "init"
      #env:
      #  SIMPLISM_DISTRO: Linux_arm64
      #  SIMPLISM_VERSION: 0.0.9

vscode:
  extensions:
    - PKief.material-icon-theme
    - PKief.material-product-icons
    - GitHub.github-vscode-theme
    - huytd.github-light-monochrome
    - wesbos.theme-cobalt2
    - aaron-bond.better-comments
    - golang.go
    - rust-lang.rust-analyzer

