# Simplism IDE
services:
  simplisme-ide:
    container_name: ${CONTAINER_NAME}
    entrypoint: ["code-server", "--auth", "none", "--host", "0.0.0.0", "--port", "${CODER_HTTP_PORT}", "/${WORKDIR}"]
    environment:
      - ABOUT="Simplism Environment with Coder"
      - XDG_DATA_HOME=/${WORKDIR}/.config
    build:         
      args:
        - GO_ARCH=${GO_ARCH}
        - GO_VERSION=${GO_VERSION}
        - TINYGO_ARCH=${TINYGO_ARCH}
        - TINYGO_VERSION=${TINYGO_VERSION}
        - EXTISM_ARCH=${EXTISM_ARCH}
        - EXTISM_VERSION=${EXTISM_VERSION}
        - SIMPLISM_VERSION=${SIMPLISM_VERSION}
        - SIMPLISM_DISTRO=${SIMPLISM_DISTRO}
        - NODE_DISTRO=${NODE_DISTRO}
        - NODE_VERSION=${NODE_VERSION}
        - HELM_VERSION=${HELM_VERSION}
        - HELM_ARCH=${HELM_ARCH}
        - K9S_VERSION=${K9S_VERSION}
        - K9S_ARCH=${K9S_ARCH}    
        - CODER_VERSION=${CODER_VERSION}
        - CODER_ARCH=${CODER_ARCH}
        - USER_NAME=${USER_NAME}
      context: ./.docker/compose
      dockerfile: Dockerfile
    init: true
    volumes:
      #- ~/.ssh:/root/.ssh
      - ~/.ssh:/home/${USER_NAME}/.ssh
      - ~/.kube:/home/${USER_NAME}/.kube
      - .:/${WORKDIR}
      - ~/.gitconfig:/etc/gitconfig
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    ports:
      - ${CODER_HTTP_PORT}:${CODER_HTTP_PORT} # Code Server HTTP port
      #- 8080:8080
